Develop
ythepaut/info406_client pull request #2
Opened 2020-02-09 11:02 UTC by Gashmob

2020-02-09 11:12 UTC, ythepaut requested changes
Est-ce que tu peux juste régler les quelques problemes du check de codefactor (Saut de ligne et default dans le switch sauf les commentaires todo qui ne sont pas graves) s'il te plaît ?

2020-02-09 11:17 UTC, ythepaut commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fenêtre principale](https://trello.com/c/Z9GcBTnk/16-fen%C3%AAtre-principale)

2020-02-09 11:18 UTC, ythepaut commented
![](https://github.trello.services/images/mini-trello-icon.png) [Création de la fenêtre de base](https://trello.com/c/vrWXwceD/10-cr%C3%A9ation-de-la-fen%C3%AAtre-de-base)

2020-02-09 12:27 UTC, RomainTHD submitted a review, later dismissed

2020-02-10 16:59 UTC, ythepaut approved these changes

2020-02-11 06:42 UTC, merged